version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_CDN_URL=${VITE_CDN_URL}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_CONTAINER_PORT}"
    container_name: frontend
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_SCHEMA=${DATABASE_SCHEMA}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - app-network
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_DOCKER_PORT}"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    networks:
      - app-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge
