version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
      - ./test/mongodb_initial_stub.json:/mongodb_initial_stub.json
    restart: always

  mongo-seed:
    image: mongo:latest
    depends_on:
      - mongodb
    volumes:
      - ./test/mongodb_initial_stub.json:/mongodb_initial_stub.json
    entrypoint: [
        'mongoimport',
        '--host', 'mongodb',
        '--db', 'afisha', 
        '--collection', 'films',
        '--file', '/mongodb_initial_stub.json',
        '--jsonArray'
      ]
    env_file:
      - .env 

volumes:
  mongo-data: